on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check .
      - name: Run Ruff format
        run: ruff format .